version: '3.1'
services:
 app:
    container_name: springboot-filestorage
    image: springboot-app
    build: ./
    ports:
      - "8085:8085"
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key
    depends_on:
      - minio
    networks:
      - drunker_network

 minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key

networks:
  default:
    external:
      name: drunker_network